stages:
  - pre
  - build_test
  - deploy

.display_env:
  before_script:
    - date
    - uname -a
    - cat /etc/os-release

pre-commit:
  stage: pre
  image:
    name: alpine:latest
  extends: .display_env
  script:
    - apk add --no-cache git npm pre-commit
    - pre-commit --version
    - pre-commit run --all-files

pycodestyle:
  stage: pre
  image:
    name: alpine:latest
  extends: .display_env
  script:
    - apk add --no-cache py3-pycodestyle
    - pycodestyle --version
    - pycodestyle --show-source --show-pep8 --statistics --verbose .

pylint:
  stage: pre
  image:
    name: alpine:latest
  extends: .display_env
  script:
    - apk add --no-cache py3-pylint py3-yaml
    - pylint --version
    - find . -name '*.py' -exec pylint {} +

ruff:
  stage: pre
  image:
    name: alpine:latest
  extends: .display_env
  script:
    - apk add --no-cache ruff
    - ruff check --unsafe-fixes --diff || echo "!!! todo !!!"
    - ruff check --output-format=full
    - ruff check --select NPY201 --fix --diff || echo "!!! todo !!!"
    - ruff check --select NPY201 --output-format=full

alpine-latest-pipx:
  stage: build_test
  image:
    name: alpine:latest
  extends: .display_env
  script:
    - apk add --no-cache pipx
    - export PATH="$PATH":~/.local/bin
    - pipx install .[shellcheck]
    - yaml2script --help
    - yaml2script all .gitlab-ci.yml
    - pipx uninstall yaml2script

alpine-latest-pip:
  stage: build_test
  image:
    name: alpine:latest
  extends: .display_env
  script:
    - apk add --no-cache py3-pip
    - pip3 install --break-system-packages .[shellcheck]
    - yaml2script --help
    - yaml2script all .gitlab-ci.yml

alpine-latest-pip-system-packages:
  stage: build_test
  image:
    name: alpine:latest
  extends: .display_env
  script:
    - apk add --no-cache py3-pip py3-yaml shellcheck
    - pip3 install --no-deps --break-system-packages .
    - yaml2script --help
    - yaml2script all .gitlab-ci.yml
    - pip3 uninstall -y --break-system-packages yaml2script
