- id: yaml2script-all
  name: yaml2script all
  entry: yaml2script all
  language: python
  files: .gitlab-ci.yml
  require_serial: true
  description: yaml2script checks all script(s) from a '.gitlab-ci.yml' file

- id: yaml2script-check
  name: yaml2script check
  entry: yaml2script check
  language: python
  always_run: true
  pass_filenames: false
  require_serial: true
  description: yaml2script checks given job(s)/script(s) from a given file (e. g. '.gitlab-ci.yml')
